# Generated by Django 5.0.3 on 2024-04-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='temp', upload_to='images'),
            preserve_default=False,
        ),
    ]
