# Generated by Django 5.0.3 on 2024-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_remove_participant_address_remove_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='address',
            field=models.CharField(default='temp', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
    ]
